server:
  port: 8889
  servlet:
    context-path: /kilnk-open-api/

spring:
  profiles:
    # 环境 dev|test|pro
    active: dev
  application:
    name: kilnk-open-api
    #==========================================jackson时间格式化==============================
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

    #==========================================http配置==================================
http:
  #最大连接数
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用10000
  staleConnectionCheckEnabled: true